### ISSUE TITLE
Fails to fetch 

### ISSUE THREAD

**Issue by dankrzeminski32** [ichard26/next-pr-number#6]
Hi, I'm attempting to get next pr number and am getting an error. 

<img width="547" alt="image" src="https://github.com/ichard26/next-pr-number/assets/76189617/eca8ab03-d890-4c4e-a5c5-88f686627006">

**Comment by ichard26** [comment]
Hey, I don't see anything in the logs that would explain why the request would've failed. Could you check the developer console for any errors?

I'm also surprised to see the tool be used out in the wild :)

**Comment by dankrzeminski32** [comment]
@ichard26 My mistake, it seems to be working correctly now. I must've had a faulty connection at the time. I'll go ahead and close this out.
